import { HttpAdapterHost, NestFactory } from '@nestjs/core';
import { AppModule } from './app.module.ts';
import { Logger } from '@nestjs/common';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import { envs } from './config/envs.ts';
import { GrpcExceptionFilter } from './common/index.ts';

async function bootstrap() {

  const logger = new Logger(`Main-Gateway`)

  const app = await NestFactory.create(AppModule, {});
  app.setGlobalPrefix('api');

  const { httpAdapter } = app.get(HttpAdapterHost);
  app.useGlobalFilters(new GrpcExceptionFilter(httpAdapter));

  // OpenAPI: UI at /api/docs, document at /api/docs-json
  const config = new DocumentBuilder()
    .setTitle('Syner API Gateway')
    .setDescription('REST gateway over the gRPC microservices (products, orders, auth, finance)')
    .setVersion('1.0')
    .addBearerAuth()
    .addTag('Auth', 'Login and organization switching. Users are created by the superadmin')
    .addTag('Organizations', 'Platform administration (superadmin): organizations and their members')
    .addTag('Products', 'Any member reads and moves stock; owner/admin manage products')
    .addTag('Alerts', 'Low-stock alerts generated by products-ms')
    .addTag('Purchase orders', 'Validated asynchronously by the saga; owner/admin create them and change their status')
    .addTag('Finance: ledger', 'Expenses (owner/admin); contributions, withdrawals, reserve and periods (owner)')
    .addTag('Finance: operations', 'Supplies, recipes, sales, payables and credit. Any member registers sales')
    .addTag('Finance: reports', 'Assumptions, policy and reports (owner/admin); the policy is changed by the owner')
    .build();
  const documentFactory = () => SwaggerModule.createDocument(app, config);
  SwaggerModule.setup('docs', app, documentFactory, {
    useGlobalPrefix: true,
    swaggerOptions: { persistAuthorization: true },
  });

  await app.listen(envs.port);
  logger.log(`App running in port ${envs.port}`)
}
await bootstrap();
